dist: xenial
language: python
python: 3.6
before_install:
  - "openssl aes-256-cbc -K $encrypted_1ffca1d148a3_key -iv $encrypted_1ffca1d148a3_iv -in config.json.enc -out config.json -d"
install: pip install -r requirements.txt
script: /bin/true
deploy:
  provider: script
  skip_cleanup: true
  script:
    - "python ./build.py"

# vim: ts=2 sts=2 sw=2 expandtab
